# Generated by Django 3.1.7 on 2021-03-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.TextField(max_length=50),
        ),
    ]
