# Generated by Django 3.1.7 on 2021-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_portfolio', '0002_auto_20210305_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
                ('date', models.TextField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
