# Generated by Django 3.1.7 on 2021-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_portfolio', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/upload'),
        ),
    ]
